spring.application.name=tcrs-app
spring.datasource.url=jdbc:postgresql://localhost:5432/tcrs
spring.datasource.username=tcrs
spring.datasource.password=tcrs_dev
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.flyway.enabled=true

# JWT configuration
jwt.expiration=86400000
jwt.cookie-name=jwt-token

# Refresh token configuration
application.security.jwt.refresh-token.expiration=1296000000
application.security.jwt.refresh-token.cookie-name=refresh-token
