spring.application.name=tcrs-app
spring.datasource.url=jdbc:postgresql://localhost:5432/tcrs
spring.datasource.username=tcrs
spring.datasource.password=tcrs_dev
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.flyway.enabled=true